run:
  timeout: 10m

issues:
  exclude-dirs:
    - .github
    - .git
# linters-settings:
#   dupl:
#     threshold: 100
#   funlen:
#     lines: -1
#     statements: 50
#   goconst:
#     min-len: 2
#     min-occurrences: 3
#   gocritic:
#     enabled-tags:
#       - diagnostic
#       - experimental
#       - opinionated
#       - performance
#       - style
#     disabled-checks:
#       - dupImport # https://github.com/go-critic/go-critic/issues/845
#       - ifElseChain
#       - octalLiteral
#       - whyNoLint
#   gocyclo:
#     min-complexity: 15
#   goimports:
#     local-prefixes: github.com/dc0d/pbtpocket/pbtpocket # TODO:
#   gomnd:
#     # don't include the "operation" and "assign"
#     checks:
#       - argument
#       - case
#       - condition
#       - return
#     ignored-numbers:
#       - '0'
#       - '1'
#       - '2'
#       - '3'
#     ignored-functions:
#       - strings.SplitN
#   govet:
#     check-shadowing: true
#   lll:
#     line-length: 140
#   misspell:
#     locale: US
#   nolintlint:
#     allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
#     allow-unused: false # report any unused nolint directives
#     require-explanation: false
#     require-specific: false

# linters:
#   disable-all: true
#   enable:
#     - bodyclose
#     # - depguard
#     - dogsled
#     - dupl
#     - errcheck
#     - exportloopref
#     - funlen
#     - gochecknoinits
#     - goconst
#     - gocritic
#     - gocyclo
#     - gofmt
#     - goimports
#     - gomnd
#     - goprintffuncname
#     - gosec
#     - gosimple
#     - govet
#     - ineffassign
#     - lll
#     - misspell
#     - nakedret
#     - noctx
#     - nolintlint
#     - staticcheck
#     - stylecheck
#     - typecheck
#     - unconvert
#     - unparam
#     - unused
#     - whitespace

#   # don't enable:
#   # - asciicheck
#   # - scopelint
#   # - gochecknoglobals
#   # - gocognit
#   # - godot
#   # - godox
#   # - goerr113
#   # - interfacer
#   # - maligned
#   # - nestif
#   # - prealloc
#   # - testpackage
#   # - revive
#   # - wsl

# issues:
#   # Excluding configuration per-path, per-linter, per-text and per-source
#   exclude-rules:
#     - path: _test\.go
#       linters:
#         - gomnd
