name: Fly Deploy

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl deploy --build-arg ICB_TOKEN=${{ secrets.ICB_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          ICB_TOKEN: ${{ secrets.ICB_TOKEN }}
